[package]
name = "ln-service"
version = "1.3.0"
edition = "2024"

[dependencies]
barretenberg = { workspace = true }
element = { workspace = true }
hash = { workspace = true }
node-interface = { workspace = true }
primitives = { workspace = true }
zk-primitives = { workspace = true }
rand = {workspace = true}
actix-web = { workspace = true }
actix-cors = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
hex = { workspace = true }
lightning-invoice = { version = "0.34", features = ["std"] }
phoenixd-rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { version = "0.7", default-features = false, features = [
    "runtime-tokio-rustls",
    "sqlite",
    "macros",
    "migrate",
    "chrono",
    "uuid",
] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
bitcoin = { version = "0.32", features = ["rand-std"] }
lightning-types = "0.3"
