name: Push check

on:
  push:

jobs:
  test-dmg:
    runs-on: macos-latest  # Free for public repos
    permissions: write-all
    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    lfs: false         # Has limits. Was introduced initially for bb binaries
      #    fetch-depth: 0     # Optional: full history if needed
      - name: Publish TEST
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        # working-directory: payy/web # re-enable on activating checkout
        run: |
          gh release create TEST -R zerosats/ciphera-wallet
          touch test.test
          gh release upload TEST test.test -R zerosats/ciphera-wallet --clobber
