name: Push check

on:
  push:

jobs:
  test-dmg:
    runs-on: macos-latest  # Free for public repos
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false         # Has limits. Was introduced initially for bb binaries
          fetch-depth: 0     # Optional: full history if needed

      - name: Publish TEST
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: ./payy/web
        run: |
          gh release create TEST -R zerosats/ciphera-wallet || true
          gh release upload TEST binaries/darwin/barretenberg-arm64-darwin.tar.gz -R zerosats/ciphera-wallet --clobber || true
